# Generated by Django 3.2.3 on 2021-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertydetails',
            options={'verbose_name_plural': 'Propertydetails'},
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='cover',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
