# Generated by Django 3.2.3 on 2021-05-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0002_auto_20210519_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='cover',
            field=models.ImageField(default='propert image', upload_to='images/'),
        ),
    ]
