# Generated by Django 3.2.3 on 2021-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0005_alter_propertydetails_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='cover',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
