# Generated by Django 3.2.3 on 2021-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0010_remove_propertydetails_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images2/'),
        ),
    ]
