# Generated by Django 3.2.3 on 2021-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0011_propertydetails_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='property_type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
