# Generated by Django 3.2.3 on 2021-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0012_propertydetails_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
