# Generated by Django 3.2.3 on 2021-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylistings', '0013_alter_propertydetails_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='Property_status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
